import {  Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});



export const metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangali} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <Navber></Navber>
        
        <main>

        {children}

        </main>
        
        </body>
    </html>
  );
}
